import { Courrier } from './types';

export const INITIAL_COURRIERS: Courrier[] = [
  {
    id: 'c1',
    type: 'ARRIVEE',
    reference: 'ARR-2026-0001',
    dateEnregistrement: '2026-06-02',
    dateCourrier: '2026-05-28',
    expeditriceDestinataire: 'Jean Dupont',
    objet: 'Candidature spontanée - Poste Développeur Front-end Senior',
    departement: 'Ressources Humaines',
    statut: 'TRAITE',
    priorite: 'MOYENNE',
    notes: 'Entretien prévu pour le 25 juin. CV et lettre de motivation archivés.',
    pieceJointeNom: 'cv_jean_dupont.pdf',
  },
  {
    id: 'c2',
    type: 'DEPART',
    reference: 'DEP-2026-0001',
    dateEnregistrement: '2026-06-05',
    dateCourrier: '2026-06-04',
    expeditriceDestinataire: 'Cabinet Audit Plus SAS',
    objet: 'Envoi des pièces comptables pour audit trimestriel Q1',
    departement: 'Finance & Comptabilité',
    statut: 'TRAITE',
    priorite: 'URGENT',
    notes: 'Dossier complet zippé envoyé par recommandé. Accusé de réception bien reçu.',
    pieceJointeNom: 'pieces_comptables_q1.zip',
  },
  {
    id: 'c3',
    type: 'ARRIVEE',
    reference: 'ARR-2026-0002',
    dateEnregistrement: '2026-06-10',
    dateCourrier: '2026-06-08',
    expeditriceDestinataire: 'GigaHost Hosting France',
    objet: 'Devis de renouvellement pour hébergement serveurs dédiés',
    departement: 'Technique & Informatique',
    statut: 'EN_COURS',
    priorite: 'URGENT',
    notes: 'À faire valider par le chef de service technique avant le 20 juin pour éviter l\'interruption.',
    pieceJointeNom: 'devis_gigahost_2026.pdf',
  },
  {
    id: 'c4',
    type: 'ARRIVEE',
    reference: 'ARR-2026-0003',
    dateEnregistrement: '2026-06-12',
    dateCourrier: '2026-06-10',
    expeditriceDestinataire: 'Tribunal de Commerce de Paris',
    objet: 'Notification de mise à jour des statuts suite AG extraordinaire',
    departement: 'Juridique & Contentieux',
    statut: 'A_TRAITER',
    priorite: 'URGENT',
    notes: 'Doit être transmis en urgence au conseil juridique externe pour vérification.',
    pieceJointeNom: 'notification_tribunal_paris_2026.pdf',
  },
  {
    id: 'c5',
    type: 'DEPART',
    reference: 'DEP-2026-0002',
    dateEnregistrement: '2026-06-14',
    dateCourrier: '2026-06-14',
    expeditriceDestinataire: 'Société Bâtiment-Parisien SARL',
    objet: 'Mise en demeure pour retard de livraison des bureaux R+2',
    departement: 'Juridique & Contentieux',
    statut: 'EN_COURS',
    priorite: 'URGENT',
    notes: 'Envoyé par huissier de justice et par courrier recommandé AR.',
    pieceJointeNom: 'mise_en_demeure_travaux.pdf',
  },
  {
    id: 'c6',
    type: 'ARRIVEE',
    reference: 'ARR-2026-0004',
    dateEnregistrement: '2026-06-15',
    dateCourrier: '2026-06-12',
    expeditriceDestinataire: 'AdVantage Communication group',
    objet: 'Proposition de campagne publicitaire - Campagne d\'été 2026',
    departement: 'Commercial & Marketing',
    statut: 'A_TRAITER',
    priorite: 'BASSE',
    notes: 'Prendre contact pour négocier la grille tarifaire après réunion interne.',
    pieceJointeNom: 'proposition_été_advantage.pdf',
  },
  {
    id: 'c7',
    type: 'DEPART',
    reference: 'DEP-2026-0003',
    dateEnregistrement: '2026-06-16',
    dateCourrier: '2026-06-15',
    expeditriceDestinataire: 'Office Depot S.A.',
    objet: 'Bon de commande fournitures de bureau - Deuxième quinzaine juin',
    departement: 'Logistique & Achats',
    statut: 'TRAITE',
    priorite: 'BASSE',
    notes: 'Payé par carte corporate. Livraison attendue sous 48h.',
    pieceJointeNom: 'bon_commande_fournitures_0642.pdf',
  },
  {
    id: 'c8',
    type: 'ARRIVEE',
    reference: 'ARR-2026-0005',
    dateEnregistrement: '2026-06-18',
    dateCourrier: '2026-06-17',
    expeditriceDestinataire: 'Direction Générale des Impôts',
    objet: 'Attestation de régularité fiscale et situation de compte',
    departement: 'Finance & Comptabilité',
    statut: 'TRAITE',
    priorite: 'MOYENNE',
    notes: 'Le quitus a été inséré dans le dossier d\'appel d\'offres public en cours.',
    pieceJointeNom: 'attestation_impots_2026.pdf',
  },
  {
    id: 'c9',
    type: 'DEPART',
    reference: 'DEP-2026-0004',
    dateEnregistrement: '2026-06-18',
    dateCourrier: '2026-06-18',
    expeditriceDestinataire: 'Madame Sophie Martin',
    objet: 'Notification d\'accord pour demande de télétravail partiel',
    departement: 'Ressources Humaines',
    statut: 'TRAITE',
    priorite: 'BASSE',
    notes: 'Avenant au contrat prêt pour signature électronique.',
    pieceJointeNom: 'avenant_teletravail_martin.pdf',
  }
];
